### ISSUE TITLE
Margins falsely set to 0 in new makeStrongestPaths() function

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#10]
This is a problem with the latest commit in the `experimental` branch.

I believe the cause of improbable ties happening in EurovisionSchulze is in line 107 of [`Schulze_Core.php`](https://github.com/julien-boudry/Condorcet/blob/d594e9570657429c5bada373057e3fe270cd8265/src/Algo/Methods/Schulze/Schulze_Core.php) in Condorcet.
```
if ($election->getPairwise()[$i]['win'][$j] > $election->getPairwise()[$j]['win'][$i]) {
    $this->StrongestPaths[$i][$j] = $this->schulzeVariant($i, $j, $election); }
```
The pairwise comparison in EurovisionSchulze gives moderately more weight to voters in smaller countries. While I haven't fully thought through the math, I suspect that these ties occur when this unequal weighing changes the pairwise winner.

Instead of inheriting this function from Schulze_Core, I now have put a modified version of it in [`EurovisionSchulze.php`](https://github.com/LiamM32/Eurovision_Condorcet/blob/fd05fc78f2ef707ed349266e90c4c05ce9ef3b71/src/Method/EurovisionSchulze.php). But instead of resulting in no more ties, it now gives me a 26-way tie.

I have some echo functions for debugging. Here is a sample of the output:
```
$StrongestPaths[25][18] = 0, Margin for UKR vs MDA is 9161.6388514424
$StrongestPaths[25][18] now set to 0

$StrongestPaths[25][19] = 0, Margin for UKR vs NOR is -4528.4027053552
$StrongestPaths[25][19] now set to 0

$StrongestPaths[25][20] = 0, Margin for UKR vs POL is 10982.5712455
$StrongestPaths[25][20] now set to 0

$StrongestPaths[25][21] = 0, Margin for UKR vs PRT is 12412.908730352
$StrongestPaths[25][21] now set to 0
```
Everywhere you see "`StrongestPaths[$i][$j]` now set to 0", it should actually be set to the float value in the previous line. Something very strange is happening on line 73.
```
$this->strongestPaths[$i][$j] = $this->schulzeVariant($i, $j, $contest);
echo("\$StrongestPaths[".$i."][".$j."] now set to ".$this->StrongestPaths[$i][$j]."\n");
```

**Comment by julien-boudry** [comment]
The Schulze Core follows very close the Schulze paper.
But I don't have the level to really understand the mathematical and logical reasons behind it. I just follow the pseudo-code and logic provided by Schulze and verify the implementation with many tests from various sources.

So, from my point of view, any changes seem highly dangerous and require understanding exactly what it's doing.
Schulze variant is the easier part, because Schulze himself hesitate between many options, and it's relatively easy to understand. But the rest...

**Comment by julien-boudry** [comment]
Are you sure that you have fixed de `NaN`problem in every case.

Because each comparison operator used with a NaN value will return false.
```php
NaN > 0; // False
NaN > -1; // false
NaN === NaN; // false
```

So, if there is any `NaN`at the line 107 (Schulze_Core) it's will be evaluated to false, then equal to 0.

**Comment by LiamM32** [comment]
> Are you sure that you have fixed de `NAN` problem in every case?

Based on the outputs I'm getting, it looks like there is no more NAN. But there is a problem visible before it gets to that line, as can be seen in the output I posted.

**Comment by julien-boudry** [comment]
Can you clarify wich dataSet and branch should I use for testing?

**Comment by julien-boudry** [comment]
Well, I don't understand why you make the modification to Schulze (and I have no opinion about that, just don't understand). ;-)

The first thing to do, it's to fix the PHP warning, without any error, we know that the problem is the logic itself, not a code problem.
```
PHP Warning:  Undefined array key 25 in C:\dev_scripts\eur\src\Method\EurovisionSchulze.php on line 68
```

If I back to the makeStrongestPaths from the Schulze_Core, its first role is to build the Strongest Path array. But here, you ask directly about the strongest path (which doesn't exist yet). Off course it's going wrong.

All are prepared with 0 in `prepareStrongestPath()` method with... 0!  So it will stay at 0, and all are equal.
The source of the warning, one time per round, it's because you remove the check $i !== $j, but it's candidate compare the himself, so key do not exist.

**Comment by LiamM32** [comment]
> Well, I don't understand why you make the modification to Schulze (and I have no opinion about that, just don't understand). ;-)

It's this line from `Schulze_Core` that doesn't make sense for EurovisionSchulze: 
```
if ($election->getPairwise()[$i]['win'][$j] > $election->getPairwise()[$j]['win'][$i]) {
```
This line makes sense if your trying to get the Condorcet winner with each vote counting equally. But this method warps the margin in each country, and gives more weight per voter to smaller countries. So it's possible for one country to beat the other in a regular pairwise comparison, but not with the way margins are calculated in this method.

Another thing I should note is that the way I rewrote it, unlike `Schulze_Core`, it allows `$this->StrongestPaths[$i][$j]` to be set to a negative value. As far as I understand, it should determine the same winner if the negative values are not changed to 0. But I may be missing something.

> The first thing to do, it's to fix the PHP warning, without any error, we know that the problem is the logic itself, not a code problem.
Line 68 (the `echo` one) only exists for debugging purposes. It will be removed when this problem is solve. Though there is the same error for line 69, which is this: `if ($this->StrongestPaths[$j][$i] <=> 0) {`

I understand why it gives me a warning, but it's only doing exactly what I want; to check if that variable is a number of neither NULL or 0, which would mean that this comparison has already been done in the opposite direction. I'm not sure how to write the same thing without an error.

> If I back to the makeStrongestPaths from the Schulze_Core, its first role is to build the Strongest Path array. But here, you ask directly about the strongest path (which doesn't exist yet). Off course it's going wrong.

My understanding of this function is that the first half of it only determines direct pairwise comparisons; the strength of the direct path, then the second half of it replaces it with the strongest path. Is this wrong?

> All are prepared with 0 in `prepareStrongestPath()` method. With... 0! So it will stay at 0, and all are equal. The source of the warning, one time per round, it's because you remove the check $i !== $j, but its candidate compares himself, so the key does not exist.
From what I can tell, it sets them to 0 to indicate that `$i` & `$j` are different values. But the check `$i !== $j` is still there.

**Comment by julien-boudry** [comment]
Put a `var_dump($this->StrongestPaths);` at the beginning of your makeStrongestPath, and you will see that your block from l.69 to 71 is neither executed.

In the second foreach, everything must be under `$i !== $j` condition, because it's impossible and the corresponding array key just does not exist, the warning comes from that.

**Comment by julien-boudry** [comment]
About the spaceship operator, it's also not doing what you expected.
https://www.php.net/manual/en/language.operators.comparison.php

In this case, it's just equivalent to `$this->StrongestPaths[$j][$i] !== 0`.

**Comment by LiamM32** [comment]
I'm not sure what is going wrong in lines 75 & 76. Here's what should be happening:
1. Line 75 in `EurovisionSchulze.php` in function `makeStrongestPaths()` makes a call to `$this->schulzeVariant($i, $j, $contest)`.
2. The `schulzeVariant` function runs, making an array of float values called `nationalMargins`. It echoes the sum of this array, which is far from 0.
3. The `schulzeVariant` function ends by returning the sum of this array.
4. Back at line 75, the array entry `$this->strongestPaths[$i][$j]` is set to the returned value.
5. On line 76, the value of `$this->strongestPaths[$i][$j]` is echoed.

As far as I see, the value of `$this->strongestPaths[$i][$j]` should be equal to the ultimate value of `array_sum($nationalMargins)` that was echoed earlier. But instead, it appears to be set to 0. I don't see why this would happen.

**Comment by LiamM32** [comment]
> Put a `var_dump($this->StrongestPaths);` at the beginning of your makeStrongestPath, and you will see that your block from l.69 to 71 is neither executed.

I put it as the first line of the function. Here is the first many lines of the output:
```
[1]=>
  array(25) {
    [0]=>
    int(0)
    [2]=>
    int(0)
    [3]=>
    int(0)
    [4]=>
    int(0)
    [5]=>
    int(0)
    [6]=>
    int(0)
    [7]=>
    int(0)
    [8]=>
    int(0)
    [9]=>
    int(0)
    [10]=>
    int(0)
    [11]=>
    int(0)
    [12]=>
    int(0)
    [13]=>
    int(0)
    [14]=>
    int(0)
    [15]=>
    int(0)
    [16]=>
    int(0)
    [17]=>
    int(0)
    [18]=>
    int(0)
    [19]=>
    int(0)
    [20]=>
    int(0)
    [21]=>
    int(0)
    [22]=>
    int(0)
    [23]=>
    int(0)
    [24]=>
    int(0)
    [25]=>
    int(0)
  }
```
So we can see that when the first key is equal to the second, the value is NULL, otherwise it's 0. I am assuming this is what it's supposed to be.

**Comment by LiamM32** [comment]
I finally found the problem. It's because line 75 doesn't set the value of `$StrongestPaths`. It sets the value of `$strongestPaths`. It's a case-sensitivity problem.

Just changing the capitalisation solves this problem. No more ties!

**Comment by LiamM32** [comment]
I finally found the problem. It's because line 75 doesn't set the value of `$StrongestPaths`. It sets the value of `$strongestPaths`. It's a case-sensitivity problem.

Just changing the capitalisation solves this problem. No more ties!

**Comment by julien-boudry** [comment]
Ok. Maybe you can encapsulate all under $i != $j instead of repeating it.
Also `[$i] != [$j]` from l.67 is a non-sense (even it's working).

I don't like (or don't understand) your `$this->StrongestPaths[$j][$i] <> 0` from l.67, look like black magic because at the beginning, they are all equal to 0, so I suspect then it's a random perspective depending of the order of candidates registering but not logic. Try to register your candidates in a different order, probably you got differents results.

**Comment by julien-boudry** [comment]
You write: `[$i] != [$j]`, it's creates two arrays containing for each one element: $j a,d $k, then you compare the array with the `!=`.
Just write $i !== $j as on your else if

Also, prefer !== operator than <>, because this last one does type juggling. Not a danger here, it's safe, but a little bit slower (nanoseconds). more strict, better it's for error detection (and here also faster).

Then instead of:
```php
                if ([$i] != [$j] AND $this->StrongestPaths[$j][$i] <> 0) {
                    $this->StrongestPaths[$i][$j] = (-1) * $this->StrongestPaths[$j][$i];
                    echo("Inverted an already-calculated margin.\n");
                } elseif ($i != $j) {
                    $this->StrongestPaths[$i][$j] = $this->schulzeVariant($i, $j, $contest);
                    echo("\$StrongestPaths[".$i."][".$j."] now set to ".$this->StrongestPaths[$i][$j]."\n");
                }
```

You can just write :
```php
                if ($i !== $j) {
                    if ($this->StrongestPaths[$j][$i] !== 0) {
                        $this->StrongestPaths[$i][$j] = (-1) * $this->StrongestPaths[$j][$i];
                        echo("Inverted an already-calculated margin.\n");
                    } else {
                        $this->StrongestPaths[$i][$j] = $this->schulzeVariant($i, $j, $contest);
                        echo("\$StrongestPaths[".$i."][".$j."] now set to ".$this->StrongestPaths[$i][$j]."\n");
                    }
                }
```

It's equivalent

**Comment by LiamM32** [comment]
Now I see. It must have said something else before, and I forgot to remove the square brackets. I forgot they were there.

Would the `!=` result in TRUE if one was set to a non-numeric value? The purpose was to make it return FALSE in such a case.

Now I'm leaning towards just taking the version from the 'makeStrongestPaths_optimisation' branch, but with the square brackets removed. Earlier I thought there may be a risk of silent bugs in the future, but it's very slightly faster. You can judge how likely it is to give wrong results with future updates to Condorcet.

**Comment by julien-boudry** [comment]
Just try inversing candidate declaration: no impact.

Probably I miss something.
But still feel that is dangerous, `makeStrongestPaths()` method is called one time. Then he will start a double loop across candidates keys ($i and $j are candidates keys, not value). At the beginning, each `$this->StrongestPaths` is populated with `0` for each arcs, so the first condition is always negative, so order of candidate key may have an impact.

I just understand that you (voluntarily) reverse `[$i][$j] `and `$[j][$i` that's smart (but hard to see!) . But still uncomfortable about that.

**Comment by julien-boudry** [comment]
> Would the `!=` result in TRUE if one was set to a non-numeric value? The purpose was to make it return FALSE in such a case.

```php
'0' <> 0; // false
'0' != 0; // false
'0' !== 0 // true
0 <> 0; // false
0 <=> 0; // 0
```

**Comment by julien-boudry** [comment]
You have many open branches for a small 1.5-person project in active development. And your skill in Git is beginner. The big merge with many branches could be painful.

I advice using fewer branches, maybe just the main branch until the first stable version. Because you can always revert a commit, checkout to it, and access history.
Even for me, it's harder to follow.

Also, maybe continue to talk to news issues or discussion if this one is resolved.
Bravo!

**Comment by LiamM32** [comment]
Thank you.

I have just merged the 'makeStrongestPaths_optimization' branch into master. Maybe this one is actually easier to read & understand, though I'm not really sure.

Should I delete the branches that I'm no longer using; 'makeStrongestPaths_optimization' & 'faster'? Or does this cause problems with git history?

**Comment by julien-boudry** [comment]
You can delete the branch locally and keep the remote branch. Or remove both, no importance.
