### ISSUE TITLE
Slow because of calls to Election::getResult()

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#5]
The version of this program in the master branch currently takes a long time because there are too many calls to `Election::getResult()`. It is in line 28 of `EurovisionSchulze.php`.
```$this->filteredPairwise[$country] = $contest->getResult(methodOptions: ['%tagFilter' => true, 'withTag' => true, 'tags' => $country])->pairwise;```
The most likely underlying problem is that this function does more than what is required during this loop. It doesn't only get one pairwise comparison, but all pairwise comparison using votes with the specified tag.

The `faster` branch has been made with a modified version of `EurovisionSchulze.php`. This one is currently much faster because it calls `Election::getResult()` fewer times; only once per voting country.

However, I put this in a new branch instead of the master because this method may no longer be optimal if Condorcet gets a new function for getting pairwise comparisons from a filtered set of votes.

**Comment by julien-boudry** [comment]
Merge your cache system, having a new version of the pairwise API can take time, and maybe no so efficient for your case, because you need cache first.

Three other little optimization strategies can help (choose one, not both):

1. Could be to call `getResult(method: 'Copeland', ...)`, because the default method is Schulze, but Copeland is a little bit faster.

2.  More ambitious and experimental (I didn't try), keep a cache system, but do like that:
```php
$filteredElection = clone $election;
$filteredElection->removeVotesByTags(tags: $country, with: false);
$pairwise = $filteredElection->getExplicitPairwise(); // Or work with the non-explicit pairwise, even faster and better, non-explicit use internal key instead of candidates names.
```

It must be better because internally, the compiler doesn't duplicate vote object memory, votes are already parsed. And you don't need to compute Reuslt, but directly the pairwise.

**Comment by LiamM32** [comment]
Are you saying that when I call `$contest->getResult()->pairwise`, I should use Copeland? Why would this make a difference? If this function only gets pairwise comparisons, not the final ranking, why would it be different for each voting method?

Or are you suggesting that I make the whole process Copeland instead of Schulze?

**Comment by julien-boudry** [comment]
It's just a little hacky optimization. Pairwise will be the same, but getResult do more than pairwise, including computing Schulze (by default) wich is slower than Copeland.

**Comment by LiamM32** [comment]
So every time it runs the Schulze method, it runs the Schulze method multiple times within the Schulze method?

**Comment by julien-boudry** [comment]
Every time it runs your method, It run many time Schulze method for nothing (because it's the filtered pairwise that you want).

**Comment by julien-boudry** [comment]
https://github.com/julien-boudry/Condorcet/pull/152
